### ISSUE TITLE
Нелогичное поведение инструкций при скролле

### ISSUE THREAD

**Issue by hudochenkov** [ideus-team/clearyourcache.info#3]
Если прокручиваешь инструкцию для одного браузера, переключаешься посмотреть инструкцию для другого браузера, а она там не с начала или не запомнила предыдущее положение скролла. У вас почему-то все инструкции прокручиваются одновременно.

**Comment by delka** [comment]
Спасибо, постараемся исправить на следующей неделе.

**Comment by chro-nos** [comment]
Исправлено
